export const OPERATORS = [
  {
    id: 1,
    name: "adición",
    operator: "+",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus aliquam lacus quis posuere.",
      "Cras vestibulum, nunc at laoreet interdum, felis felis viverra enim, vitae mollis lacus ex sit amet sem.",
      "Aliquam odio tellus, semper eu rhoncus non, egestas eu purus. Mauris eu ligula ultricies, fringilla diam nec, dignissim est. Quisque faucibus velit orci, sit amet ultrices dolor rutrum vitae.",
    ],
    code: `print(1 + 1) # 2\nprint("hola" + "mundo") # holamundo`,
    docs: "https://docs.python.org/3/reference/lexical_analysis.html#operators",
  },
  { id: 2, name: "sustracción", operator: "-" },
  { id: 3, name: "multiplicación", operator: "*" },
  { id: 4, name: "división", operator: "/" },
  { id: 5, name: "división entera", operator: "//" },
  { id: 6, name: "módulo", operator: "%" },
  { id: 7, name: "potencia", operator: "**" },
  { id: 8, name: "asignación", operator: "=" },
  { id: 9, name: "", operator: "+=" },
  { id: 10, name: "", operator: "-=" },
  { id: 11, name: "", operator: "*=" },
  { id: 12, name: "", operator: "/=" },
  { id: 13, name: "", operator: "//=" },
  { id: 14, name: "", operator: "%=" },
  { id: 15, name: "", operator: "**=" },
  { id: 16, name: "igualdad", operator: "==" },
  { id: 17, name: "diferente", operator: "!=" },
  { id: 18, name: "mayor que", operator: ">" },
  { id: 19, name: "mayor o igual que", operator: ">=" },
  { id: 20, name: "menor que", operator: "<" },
  { id: 21, name: "menor o igual que", operator: "<=" },
  { id: 22, name: "and", operator: "and" },
  { id: 23, name: "or", operator: "or" },
  { id: 24, name: "not", operator: "not" },
  { id: 25, name: "in", operator: "in" },
  { id: 26, name: "is", operator: "is" },
  { id: 27, name: "walrus", operator: ":=" },
  { id: 28, name: "ellipsis", operator: "..." },
  { id: 29, name: "bitwise and", operator: "&" },
  { id: 30, name: "bitwise or", operator: "|" },
  { id: 31, name: "bitwise xor", operator: "^" },
  { id: 32, name: "bitwise not", operator: "~" },
  { id: 33, name: "bitwise left shift", operator: "<<" },
  { id: 34, name: "bitwise right shift", operator: ">>" },
];
